#if defined _TF2UCC_PLUGININFO_INC
 #endinput
#endif
#define _TF2UCC_PLUGININFO_INC

#pragma semicolon 1
#pragma newdecls required

#define PLUGIN_NAME "Ultimate Chicken Cow"
#define PLUGIN_AUTHOR "[X6] Herbius"
#define PLUGIN_DESCRIPTION "Modeled after that hazardous platformer you can get on Steam."
#define PLUGIN_VERSION "1.0.0.0"
#define PLUGIN_URL "http://x6herbius.com/"

#define PLUGIN_IDENT "tf2ucc"

public Plugin myinfo =
{
    name = PLUGIN_NAME,
    author = PLUGIN_AUTHOR,
    description = PLUGIN_DESCRIPTION,
    version = PLUGIN_VERSION,
    url = PLUGIN_URL
}
