/* =================================================
    TF2Extra - X6Herbius, 11/02/2017
   ================================================= */

#if defined _TF2EXTRA_INC
 #endinput
#endif
#define _TF2EXTRA_INC

#pragma semicolon 1
#pragma newdecls required

#include <tf2>

public const char TF2Ex_ClassName[][] =
{
    "unknown",
    "scout",
    "sniper",
    "soldier",
    "demoman",
    "medic",
    "heavyweapons",
    "pyro",
    "spy",
    "engineer"
};