#if defined _TF2DM_PLUGININFO_INC
 #endinput
#endif
#define _TF2DM_PLUGININFO_INC

#pragma semicolon 1
#pragma newdecls required

#define PLUGIN_NAME "Team Fortress 2: Deathmatch"
#define PLUGIN_AUTHOR "[X6] Herbius"
#define PLUGIN_DESCRIPTION "Deathmatch-style gameplay with weapon pickups and power-ups."
#define PLUGIN_VERSION "1.0.0.0"
#define PLUGIN_URL "http://x6herbius.com/"

public Plugin myinfo = 
{
    name = PLUGIN_NAME,
    author = PLUGIN_AUTHOR,
    description = PLUGIN_DESCRIPTION,
    version = PLUGIN_VERSION,
    url = PLUGIN_URL
}