#if defined _ARENAROULETTE_PLUGIN_INFO_INC
 #endinput
#endif

#define _ARENAROULETTE_PLUGIN_INFO_INC

#pragma semicolon 1
#pragma newdecls required

#define PLUGIN_NAME "Arena Roulette"
#define PLUGIN_AUTHOR "NoodleCollie"
#define PLUGIN_DESCRIPTION "Play a variety of arena mini-modes."
#define PLUGIN_VERSION "1.0.0.0"
#define PLUGIN_URL "https://github.com/noodlecollie/smplugins/tree/master/ArenaRoulette"

#define PLUGIN_IDENT "arenaroulette"
#define LIBRARY_NAME "ArenaRoulette"

public Plugin myinfo =
{
    name = PLUGIN_NAME,
    author = PLUGIN_AUTHOR,
    description = PLUGIN_DESCRIPTION,
    version = PLUGIN_VERSION,
    url = PLUGIN_URL
}
