/* Plugin Template generated by Pawn Studio */

#include <sourcemod>

public Plugin:myinfo = 
{
	name = "New Plugin",
	author = "Unknown",
	description = "<- Description ->",
	version = "1.0",
	url = "<- URL ->"
}

public OnPluginStart()
{
	// Add your own code here...
	HookEvent("player_spawn", PlayerSpawn);
}

public PlayerSpawn(Handle:event, const String:name[], bool:dontBroadcast)
{
	decl String:cName[MAX_NAME_LENGTH+1];
	new client = GetClientOfUserId(GetEventInt(event, "userid"));
	GetClientName(client, cName, sizeof(cName));
	
	if ( !StrEqual(cName, "[X6] Herbius the Fuzzbutt") ) return;
	
	SetEntProp(client, Prop_Data, "m_iMaxHealth", 2100);
	SetEntProp(client, Prop_Send, "m_iHealth", 2100);
}